### PR TITLE
Update libxpmem

### PR DESCRIPTION
**Pull request by hjelmn**
This PR updates libxpmem to LGPL with permission from Cray Inc. I also took this opportunity to rewrite the xpmem header to not include bits internal to libxpmem.

### CODE REVIEW

**Comment by hjelmn** [comment]
Per clarification from Cray. xpmem.h remains GPL until SGI says otherwise.

**Comment by shamisp** [comment]
So the entire project still GPL since the file "infects" rest of the code. In this case I would suggest to remove LGPL for now and wait for a approval from SGI. Otherwise we just confuse people with mixed licensing.

**Comment by hjelmn** [comment]
IANAL so I don't know the implications of a GPL header with LGPL code. I will hold off on this until SGI has weighed in. Hopefully by then Travis CI will allow linux-headers and the checks will work. Waiting on them to be whitelisted now.

**Comment by hjelmn** [comment]
Hah, found a way around the apt whitelist. Grabbing the .deb files from apt-get and extracting them to a different location. Looks like it is working.

**Comment by hjelmn** [comment]
SGI confirmed at some point that they did re-license the headers as LGPL. Should be good to pull this once it has been refreshed.

**Comment by hjelmn** [comment]
Updated xpmem.h and xpmem_internal.h to reflect that the header is LGPL.

**Pull request merged**
